package Modelo;
// Generated May 28, 2017 8:18:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Meter generated by hbm2java
 */
public class Meter  implements java.io.Serializable {


     private Integer id;
     private Location location;
     private String ip;
     private String name;
     private String comments;
     private String macAddress;
     private Set digitalcontrols = new HashSet(0);
     private Set measurements = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set configs = new HashSet(0);

    public Meter() {
    }

    public Meter(Location location, String ip, String name, String comments, String macAddress, Set digitalcontrols, Set measurements, Set logs, Set configs) {
       this.location = location;
       this.ip = ip;
       this.name = name;
       this.comments = comments;
       this.macAddress = macAddress;
       this.digitalcontrols = digitalcontrols;
       this.measurements = measurements;
       this.logs = logs;
       this.configs = configs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }
    public Set getDigitalcontrols() {
        return this.digitalcontrols;
    }
    
    public void setDigitalcontrols(Set digitalcontrols) {
        this.digitalcontrols = digitalcontrols;
    }
    public Set getMeasurements() {
        return this.measurements;
    }
    
    public void setMeasurements(Set measurements) {
        this.measurements = measurements;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getConfigs() {
        return this.configs;
    }
    
    public void setConfigs(Set configs) {
        this.configs = configs;
    }




}


