package Modelo;
// Generated Jun 11, 2017 11:33:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Quantity generated by hbm2java
 */
public class Quantity  implements java.io.Serializable {


     private Integer id;
     private Magnitude magnitude;
     private String description;
     private Set measures = new HashSet(0);

    public Quantity() {
    }

    public Quantity(Magnitude magnitude, String description, Set measures) {
       this.magnitude = magnitude;
       this.description = description;
       this.measures = measures;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Magnitude getMagnitude() {
        return this.magnitude;
    }
    
    public void setMagnitude(Magnitude magnitude) {
        this.magnitude = magnitude;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMeasures() {
        return this.measures;
    }
    
    public void setMeasures(Set measures) {
        this.measures = measures;
    }




}


